[package]
name = "lindera"
version = "0.7.1"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "Jun Ohtani <johtani@gmail.com>",
    "ikawaha",
    "Tomoko Uchida <tomoko.uchida.1111@gmail.com>"
    ]
edition = "2018"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.3"
byteorder = "1.3"
encoding = "0.2"
serde = {version="1.0", features = ["derive"] }
serde_json = "1.0"

lindera-core = { version = "0.7", path = "../lindera-core" }
lindera-dictionary = { version = "0.7", path = "../lindera-dictionary" }
lindera-ipadic = { version = "0.7", path = "../lindera-ipadic" }
lindera-ipadic-builder = { version = "0.7", path = "../lindera-ipadic-builder" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[profile.release]
lto = true
opt-level = "z"